env:
  global:
    - secure: shn39kwobOKkJObo2zKF+vcrEu02tfdlCvXHTm5gowqR31u+S948Qx9G5yjQz3yoFUZZ8ght7Cr64bhWa3naubfSC2VPUSqf52VUv/gvkB4bCMeMbRZ7u38n3tAa7JPPJITEDBi7XB3q4oK8tCW5z2ly+XV98swbODLFSYNSJ0aUoWhsUSNm6iXlfy6orqTpbDUJ3f6mP5trHFqE06HPihqnOKcyitA99odsCpzui1VcEGj22ODASLc0cWIIBWyS3abGkswYWhlL0qZn3rd1rH5L66yxh80jLdyAwogR9A4x7LRuQEGSjRWuGG+ne5qNky3m/KQggiZj3IcZwhi/PDlK9HDNWPrs6ef7z6Qq+LSxymrkGizE+r5UZFhqSOELnH2d4UHzgOVAXqXcdUhsJ3eLASQrfodFQVeG9OKFPqVk61rm87hf4Bbl84Tlb3Esyblh5ckpZehwrvwi7HG3MHZ8RHZJA/z6BcHsBDtJs7alrSkIgGhcodRo/fzrvIBhmxM866cSuKTVjDDRGmjPCpr0+Os7SA9BnTAVArpnoFYAvNJV1ZY03K7JhhBeedWzOWQzqfhKi2Ysivb0NUb76UhH1YypIJtfCbHdYgXmgSsz5zKrVIXp7E1P/K4GXn4MfPBcNiwWeo2BLRA/tXSRN3zzTinOlhjTJEj5f3x+JYE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/lightswitch05_hosts_ads-and-tracking-extended
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
